########################### docker-compose.yml ###########################
# Para correr este archivo:
# docker compose up
#
# Para correr en segundo plano:
# docker compose up -d
#version: '3.3'

services:
  dbserver:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: labcom,2015
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "/run/desktop/mnt/host/c/db-distribuida:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    expose:
      - 5432

  # Exportador de métricas de PostgreSQL para Prometheus
  postgresql-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
        DATA_SOURCE_NAME: "dbserver:5432/postgres?sslmode=disable"
        DATA_SOURCE_USER: "postgres"
        DATA_SOURCE_PASSWORD: "labcom,2015"
    expose:
      - 9187 # Exponer el puerto 9187 del contenedor a la red interna de Docker.


  consul:
    image: consul:1.15.4
    command:
      agent -dev
      -ui
      -bind 0.0.0.0
      -client 0.0.0.0
    ports:
      - "8500:8500"
    expose:
      - 8500


  proxy:
    image: traefik:3.4.1
    command: |
      --api.insecure=true
      --api.dashboard=true
      --providers.ConsulCatalog.exposedByDefault=false
      --providers.consulCatalog.refreshInterval=5s
      --providers.consulCatalog.endpoint.address=consul:8500
      --entrypoints.metrics.address=:"8082"
      --entrypoints.http.address=:"80"
      --metrics.prometheus=true
      --metrics.prometheus.entryPoint=metrics
    ports:
      - "8888:8080" # Traefik dashboard
      - "8080:80"   # HTTP, host:contenedor
      - "8082:8082" # Metrics, host:contenedor
    expose:
      - 80 # Exponer el puerto 80 del contenedor a la red interna de Docker.
    depends_on:
     - consul


  authors:
    #image: jcestrella/app-authors:latest
    image: jcestrella/app-authors:cors
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: labcom,2015
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/postgres
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    # Comento el mapeo ya que uso Traefik para usar el proxy inverso.
    # http://127.0.0.1:8080/app-authors/authors
    # ports:
    #   - "9090:8080" # host:contenedor
    expose:
      - 8080 # Exponer el puerto 8080 del contenedor a la red interna de Docker.
    deploy:
      replicas: 1
    depends_on:
      - dbserver
      - consul
    entrypoint: >
      sh -c "
      apk add --no-cache curl bash &&
      curl -o /usr/local/bin/wait-for-it https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
      chmod +x /usr/local/bin/wait-for-it &&
      /usr/local/bin/wait-for-it dbserver:5432 -- java -jar /app/app.jar
      "



  books:
    image: jcestrella/app-books:cors
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: labcom,2015
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/postgres
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      #AUTHORS_URL: http://authors3:8080
    #ports:
    #  - "9091:8080" # host:contenedor
    expose:
      - 8080 # Exponer el puerto 8080 del contenedor a la red interna de Docker.
    depends_on:
      - dbserver
      - consul
    entrypoint: >
      sh -c "
      curl -o /usr/local/bin/wait-for-it https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
      chmod +x /usr/local/bin/wait-for-it &&
      /usr/local/bin/wait-for-it dbserver:5432 -- java -jar /app/app.jar
      "



  customers:
    image: jcestrella/app-customers:cors
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: labcom,2015
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/postgres
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    #ports:
    #  - "9092:7070" # host:contenedor
    expose:
      - 8080 
    depends_on:
      - dbserver
      - consul
      - books  
    entrypoint: >
      sh -c "
      curl -o /usr/local/bin/wait-for-it https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
      chmod +x /usr/local/bin/wait-for-it &&
      /usr/local/bin/wait-for-it dbserver:5432 -- 
      /usr/local/bin/wait-for-it consul:8500 -- 
      java -jar /app/app.jar
      "



  front:
    image: jcestrella/app-front:latest
    ports:
      - "4000:80"  # Puerto del frontend Vue.js
    expose:
      - 80
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
      - VITE_AUTHORS_API_URL=http://localhost:8080/app-authors
      - VITE_BOOKS_API_URL=http://localhost:8080/app-books
      - VITE_CUSTOMERS_API_URL=http://localhost:8080/app-customers
    depends_on:
      - proxy
      - authors
      - books
      - customers


  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "./configs:/etc/prometheus"
    ports:
      - "9090:9090"
    expose:
      - 9090


  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin


# Acceder a Grafana: http://localhost:3000
# Acceder a Prometheus: http://localhost:9090
# Acceder al dashboard de Traefik: http://localhost:8888
# Acceder a Consul: http://localhost:8500
# Acceder a Traefik dashboard: http://localhost:8888/dashboard/#/

# Frontend Vue.js:
# Acceder al frontend: http://localhost:4000

# Authors:
# Acceder a la aplicación de autores: http://localhost:8080/app-authors/authors
# Salud autores:                      http://localhost:8080/app-authors/q/health

# Books:
# Acceder a la aplicación de libros: http://localhost:8080/app-books/books
# Salud libros:                      http://localhost:8080/app-books/q/health

# Customers:
# Acceder a la aplicación de customers: http://localhost:8080/app-customers/orders
# Salud customers:                      http://localhost:8080/app-customers/q/health
# Órdenes por cliente:                  http://localhost:8080/app-customers/orders/customer/1
# Orden específica:                     http://localhost:8080/app-customers/orders/1

# devui: http://localhost:8080/q/dev-ui/extensions

# Para prometheus, la URL es http://prometheus:9090