rootProject.name = "prog-distribuida-dc"
include("ejemplo01-cdi")
include("ejemplo02-rest")
include("ejemplo02-custom-rest")
include("ejemplo03-custom-rest")
include("appAuthor")
include("app-books")
include("app-authors")
include("app-customers")
include("customers")
