quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=labcom,2015
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres

quarkus.http.port=8080

consul.host=127.0.0.1
consul.port=8500

# Configuración para Micrometer y Prometheus
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics

# Configuración para Stork - Descubrimiento de servicios
quarkus.stork.books-api.service-discovery.type=consul
quarkus.stork.books-api.service-discovery.consul-host=${consul.host}
quarkus.stork.books-api.service-discovery.consul-port=${consul.port}
quarkus.stork.books-api.service-discovery.application=app-books
quarkus.stork.books-api.service-discovery.refresh-period=5s

# Configuración CORS para permitir peticiones desde el frontend
quarkus.http.cors=true
quarkus.http.cors.origins=*

