# Configuración CORS para permitir peticiones desde el frontend
quarkus.http.cors=true
quarkus.http.cors.origins=*

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=labcom,2015
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres

# Activa el registro (logging) de las sentencias SQL ejecutadas por Hibernate ORM
quarkus.hibernate-orm.log.sql=true
# Formatea las sentencias SQL en el log para mejor legibilidad
quarkus.hibernate-orm.log.format-sql=true
# Muestra las sentencias SQL en la consola (�til para depuraci�n)
quarkus.hibernate-orm.show-sql=true

# ojo
#quarkus.hibernate-orm.database.generation=update

# tiene on-migrate=true en vez de on-start=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true

quarkus.http.port=8080

# Configuraci�n para Consul
consul.host=127.0.0.1
consul.port=8500

# Configuraci�n para Micrometer y Prometheus
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics
