-- SQL Manager Lite for PostgreSQL 6.6.1.58897
-- ---------------------------------------
-- Host      : localhost
-- Database  : distribuida
-- Version   : PostgreSQL 17.4 on x86_64-windows, compiled by msvc-19.41.34120, 64-bit

CREATE TABLE public.authors (
    id serial NOT NULL,
    name varchar(255),
    version integer
)
WITH (oids = false);

ALTER TABLE ONLY public.authors ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.authors ALTER COLUMN name SET STATISTICS 0;
ALTER TABLE ONLY public.authors ALTER COLUMN version SET STATISTICS 0;

CREATE TABLE public.books_authors (
    books_isbn varchar(255) NOT NULL,
    authors_id integer NOT NULL
)
WITH (oids = false);

ALTER TABLE ONLY public.books_authors ALTER COLUMN books_isbn SET STATISTICS 0;
ALTER TABLE ONLY public.books_authors ALTER COLUMN authors_id SET STATISTICS 0;

CREATE TABLE public.books (
    isbn varchar(255) NOT NULL,
    title varchar(128),
    price numeric(12,2),
    version integer
)
WITH (oids = false);

ALTER TABLE ONLY public.books ALTER COLUMN isbn SET STATISTICS 0;
ALTER TABLE ONLY public.books ALTER COLUMN title SET STATISTICS 0;
ALTER TABLE ONLY public.books ALTER COLUMN price SET STATISTICS 0;
ALTER TABLE ONLY public.books ALTER COLUMN version SET STATISTICS 0;

CREATE TABLE public.inventory (
    isbn varchar(255) NOT NULL,
    sold integer,
    supplied integer
)
WITH (oids = false);

ALTER TABLE ONLY public.inventory ALTER COLUMN isbn SET STATISTICS 0;
ALTER TABLE ONLY public.inventory ALTER COLUMN sold SET STATISTICS 0;
ALTER TABLE ONLY public.inventory ALTER COLUMN supplied SET STATISTICS 0;

CREATE TABLE public.customers (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(64),
    email varchar(64),
    version integer
)
WITH (oids = false);

ALTER TABLE ONLY public.customers ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.customers ALTER COLUMN name SET STATISTICS 0;
ALTER TABLE ONLY public.customers ALTER COLUMN email SET STATISTICS 0;
ALTER TABLE ONLY public.customers ALTER COLUMN version SET STATISTICS 0;

CREATE TABLE public.line_items (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id integer,
    quantity integer,
    isbn varchar(64)
)
WITH (oids = false);

ALTER TABLE ONLY public.line_items ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.line_items ALTER COLUMN order_id SET STATISTICS 0;
ALTER TABLE ONLY public.line_items ALTER COLUMN quantity SET STATISTICS 0;
ALTER TABLE ONLY public.line_items ALTER COLUMN isbn SET STATISTICS 0;

CREATE TABLE public.purchase_orders (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id integer,
    total integer,
    status smallint,
    placed_on timestamp without time zone,
    delivered_on timestamp without time zone
)
WITH (oids = false);

ALTER TABLE ONLY public.purchase_orders ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN customer_id SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN total SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN status SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN placed_on SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN delivered_on SET STATISTICS 0;

-- Claves primarias y foráneas

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT author_pkey
    PRIMARY KEY (id);

ALTER TABLE ONLY public.books_authors
    ADD CONSTRAINT pk_books_authors
    PRIMARY KEY (books_isbn, authors_id);

ALTER TABLE ONLY public.books_authors
    ADD CONSTRAINT fk_books_authors_on_authors
    FOREIGN KEY (authors_id) REFERENCES authors(id);

ALTER TABLE ONLY public.books
    ADD CONSTRAINT pk_books
    PRIMARY KEY (isbn);

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT pk_inventory
    PRIMARY KEY (isbn);

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT fk_inventory_on_isbn
    FOREIGN KEY (isbn) REFERENCES books(isbn);

ALTER TABLE ONLY public.books_authors
    ADD CONSTRAINT fk_books_authors_on_books
    FOREIGN KEY (books_isbn) REFERENCES books(isbn);

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT pk_customers
    PRIMARY KEY (id);

ALTER TABLE ONLY public.line_items
    ADD CONSTRAINT pk_line_items
    PRIMARY KEY (id);

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT pk_purchase_orders
    PRIMARY KEY (id);

ALTER TABLE ONLY public.line_items
    ADD CONSTRAINT fk_line_items_on_order
    FOREIGN KEY (order_id) REFERENCES purchase_orders(id);

ALTER TABLE ONLY public.line_items
    ADD CONSTRAINT fk_line_items_on_book
    FOREIGN KEY (isbn) REFERENCES books(isbn);

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT fk_purchase_orders_on_customer
    FOREIGN KEY (customer_id) REFERENCES customers(id);

-- Comentario de esquema
COMMENT ON SCHEMA public IS 'standard public schema';