############################ Dockerfile para la aplicacion Frontend ##############################

FROM node:20-alpine AS build-stage

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.24-alpine AS production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

############################ Comandos para construir la imagen Docker ##############################

#      docker build -t jcestrella/app-front . && docker push jcestrella/app-front