global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'authors-app'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['authors:8080']

  - job_name: 'prometheus'
    static_configs:
      #- targets: ['localhost:9090']
        - targets: ['prometheus:9090'] # TODO: Cambie localhost por el nombre del servicio en Docker Compose


  - job_name: 'proxy'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['proxy:8082']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgresql-exporter:9187']

